# Generated by Django 5.0.1 on 2024-02-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboards', '0002_scripts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scripts',
            name='script',
            field=models.TextField(),
        ),
    ]
