# Generated by Django 5.0.1 on 2024-04-02 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kt_auth', '0002_profile_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
