# Generated by Django 5.0.1 on 2024-04-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kt_auth', '0003_profile_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_timezone',
            field=models.CharField(blank=True, default='UTC', max_length=50),
        ),
    ]
