# Generated by Django 5.0.1 on 2024-04-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kt_auth', '0004_alter_profile_user_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='user_language',
            field=models.CharField(default='en', max_length=59),
        ),
    ]
